baseurl = "http://tobias-schmidt.site/"
languageCode = "en"
title = "Tobias Schmidt"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/mrtobe\">Tobias Schmidt</a> 2016"
disqusShortname = ""
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/mrtobe"
fa_icon = "fa-github"

[[params.social]]
url = "https://de.linkedin.com/in/tobias-schmidt-565b6396"
fa_icon = "fa-linkedin"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
