languageCode = "en-us"
title = "Oana Schmidt"
baseurl = "http://oana-schmidt.de/"
theme = "aerial"

[params]
  name = "Oana Schmidt"
  about = "Medical Student &nbsp;&bull;&nbsp; Photographer"
  copyright = "Oana Schmidt"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "github.com/oana91"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:oa.negulescu@googlemail.com"
